### ISSUE TITLE
classification tab bug

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#38]
The heirarchy presented in the classification tab is displaying incorrect child terms below the search term.
See attached screenshots.

![screen shot 2015-06-09 at 2 12 46 pm](https://cloud.githubusercontent.com/assets/957012/8069776/b0a21cc6-0eb1-11e5-9cb2-feb6749b3968.png)
![screen shot 2015-06-09 at 2 08 48 pm](https://cloud.githubusercontent.com/assets/957012/8069775/b0a112f4-0eb1-11e5-8c14-b24eb0e4e109.png)

**Comment by balhoff** [comment]
I think the results are "correct" but need to be refined so that they don't seem unexpected. The classification includes not only Uberon terms but also those from ZFA, MGI, and XAO. This reflects the actual connections in the data. Also, annotations coming from MODs are annotated using these other ontologies.
I'm not yet sure what the ideal approach is. The MOD data can't be directly translated to a specific Uberon term (this was the case for ZFA > TAO but is not at all the case now), so it is most straightforward to represent the real tangled web.
On the other hand there are some nuisance terms in the classification that I should hide ("has_part some hypobranchial 1 bone"). Perhaps there should be an indicator of the source ontology next to all the terms.

**Comment by wdahdul** [comment]
Yes, some indication of the source ontology (or simply taxon? eg., Danio rerio) would be helpful.

**Comment by wdahdul** [comment]
Related to this, the labels for FMA terms don't appear in the classification. See in the screenshot above.

**Comment by balhoff** [comment]
Only Uberon terms should be shown in the anatomy classification now. Fixed by c10c950c051aabed9810d243aa11c1b2ed35239a.
